# -- phpbb_portal_config
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_attachments_number', '10', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_right_collumn_width', '180', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_left_collumn_width', '180', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_max_online_friends', '8', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_max_most_poster', '8', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_max_last_member', '10', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_poll_topic_id', '0', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_last_visited_bots_number', '8', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_pay_acc', 'your@paypal.com', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_pay_s_block', '0', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_pay_c_block', '0', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_recent_title_limit', '30', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_max_topics', '10', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_news_forum', '1,2', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_news_length', '550', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_number_of_news', '4', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_number_of_announcments', '2', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_announcments_day', '0', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_announcments_length', '600', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_global_announcments_forum', '0', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_word_graph_word_counts', '0', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_word_graph_max_words', '50', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_word_graph_ratio', '2', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_version', 'Plain 0.2', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_welcome_intro', '&lt;img src=&quot;images/Behinde.gif&quot; width=&quot;100&quot; height=&quot;75&quot; vspace=&quot;10&quot;  hspace=&quot;10&quot; align=&quot;left&quot;&gt;&lt;div align=&quot;left&quot;&gt;&lt;center&gt;Welcome to &lt;b&gt;phpBB3 Portal XL 5.0&lt;/b&gt;&lt;/center&gt;&lt;br /&gt;We aim to make phpBB3 Portal XL 5.0 as fast, user friendly and error free as possible! At the same time, we will offer a quick and efficient alternative to other phpBB3 related portals... because we believe open source matters.&lt;br /&gt;&lt;br /&gt;&lt;b&gt;Portal XL 5.0 &lt;/b&gt; installed successfully.&lt;br /&gt;Please visit you Admincenter for finetuning now.&lt;br&gt;&lt;br&gt;Thank you, and enjoy!', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_welcome_back', '&lt;img src=&quot;images/Behinde.gif&quot; width=&quot;100&quot; height=&quot;75&quot; vspace=&quot;10&quot;  hspace=&quot;10&quot; align=&quot;left&quot;&gt;&lt;div align=&quot;left&quot;&gt;We are excited to have you join our community. We have given you many options to choose from, all with the goal of allowing you to communicate with other community members. You can expect as much help as you need and plenty of personal attention to help make sure your Portal XL 5.0 is as successfull as possible.&lt;br /&gt;&lt;br /&gt;Be sure to check this website as often as possible. We will be posting changes and additions throughout the week. Thank you for your time, and we hope you will bookmark this site! This text comes out of the database!&lt;/div&gt;', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_drag_drop', '0', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_visit_counter', '2', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_weather_zipcode', '41334', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_weather_alternate_url1', '', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_weather_alternate_url', '&lt;a href=&quot;http://weerkamer.nl/&quot; target=&quot;_BLANK&quot;&gt;&lt;img src=&quot;http://weerkamer.nl/weer/weeranimatie/weeranimatie.fpl&quot; width=&quot;110&quot; height=&quot;69&quot; border=&quot;0&quot;&gt;&lt;/a&gt;', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_weather_ger', '0', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_weather_alternate_url2', '', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_index_forum_block', '0', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_index_left_column', '0', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_index_left_collumn_width', '180', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_index_right_column', '1', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_index_right_collumn_width', '180', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_poll_forum_id', '2', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_poll_post_id', '0', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_index_layout', '1', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_max_lastvisits', '5', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_display', '1', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee', '1', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_fontcolor', '#ff0000', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_fontsize', '11', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_direction', 'left', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_speed', '2', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_text', 'Database driven 8O &lt;b&gt;marquee&lt;/b&gt; text includes chosable color, fontsize, scroll- direction and speed 8). Up to 1000 characters plain text is possible, html is allowed ;). Configuration comlete Portal''s ACP aware ...', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_scrolldelay', '2', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_align', 'middle', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_behavior', 'scroll', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_bgcolor', '', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_height', '', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_width', '90%', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_hspace', '', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_vspace', '', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_loop', '', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_redirect_url_time', '', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_redirect_url_adress', '', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_refresh', '', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_pragma', '', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_keywords', '', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_description', '', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_picture_resize', '450', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_layout', '1', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_author', '', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_identifier_url', '', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_reply_to', '', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_revisit_after', '15', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_category', '', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_copyright', '', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_generator', '', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_robots', 'index, follow, noodp', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_distribution', 'Global', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_date_creation_year', '2007', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_date_creation_month', '05', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_date_creation_day', '01', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_date_revision_year', '2007', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_date_revision_month', '08', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_meta_date_revision_day', '21', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_feeds_cache_time', '3600', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_feeds_items_limit', '5', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_feeds_random_limit', '4', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_acronyms_allow', '1', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_pages_left_collumn_width', '180', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_pages_right_collumn_width', '180', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_partners_display_value', '3', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_left_column', '1', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_right_column', '1', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_pages_layout', '1', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_pages_left_column', '1', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_pages_right_column', '1', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_counter_ip_logfile', 'images/counter/ip.txt', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_counter_digits_ani_path', 'images/counter/digits_ani', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_counter_digits_path', 'images/counter/digits', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_counter_block_ip', '1', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_counter_digits_height', '22', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_counter_digits_width', '16', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_counter_digits_number', '6', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_counter_block_time', '60', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_counter_display_mode', '1', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_counter_display_stats', '1', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_news_show_last_post', '1', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_show_tool_tips', '1', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_news_repository', '0', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_news_permissions', '0', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_show_all_news', '0', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_announcement_repository', '0', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_announcements_permissions', '0', 0);
INSERT INTO phpbb_portal_config (config_name, config_value, is_dynamic) VALUES ('portal_show_all_announcements', '0', 0);

# -- phpbb_portal_forumadds
INSERT INTO phpbb_portal_forumadds (adds_id, adds_name, adds_code, adds_show_forums, adds_show_all_forums, adds_active, adds_views, adds_max_views, adds_position) VALUES (1, 'Curabitur ac lorem et', 'This is a big joke which appears after every first message for guest users, switchable of cource... :).', 2, 1, 3, 1, 500, 1);
INSERT INTO phpbb_portal_forumadds (adds_id, adds_name, adds_code, adds_show_forums, adds_show_all_forums, adds_active, adds_views, adds_max_views, adds_position) VALUES (2, 'Lorem ipsum dolor sit amet', 'This joke is much bigger and will be displayed after every message visible for guest only. Should it switchable too? ;).', 2, 1, 3, 1, 500, 2);

# -- phpbb_portal_links
INSERT INTO phpbb_portal_links (links_id, links_img, links_name, links_url, links_view, links_order) VALUES (1, 'square_orange.gif', 'phpBB Worldwide', 'http://www.phpbb.com/', '1', 2);
INSERT INTO phpbb_portal_links (links_id, links_img, links_name, links_url, links_view, links_order) VALUES (2, 'square_red.gif', 'Easy Tutorials', 'http://www.easytutorials.org/', '1', 15);
INSERT INTO phpbb_portal_links (links_id, links_img, links_name, links_url, links_view, links_order) VALUES (3, 'square_brown.gif', 'DaMysterious Portal XL 5.0', 'http://www.portalxl.nl/forum/', '1', 17);

# -- phpbb_portal_menu
INSERT INTO phpbb_portal_menu (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (1, 'icon_menu_004.gif', 'Portal', 'portal.php', '1', 1);
INSERT INTO phpbb_portal_menu (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (2, 'icon_menu_014.png', 'Forum', 'index.php', '1', 2);
INSERT INTO phpbb_portal_menu (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (3, 'icon_menu_001.gif', 'Memberlist', 'memberlist.php', '3', 26);
INSERT INTO phpbb_portal_menu (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (4, 'icon_menu_027.gif', 'Staff', 'memberlist.php?mode=leaders', '3', 25);
INSERT INTO phpbb_portal_menu (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (5, 'icon_menu_013.png', 'Bookmarks', 'ucp.php?i=main&amp;mode=bookmarks', '3', 24);
INSERT INTO phpbb_portal_menu (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (6, 'icon_menu_019.png', 'Profile', 'ucp.php', '3', 23);
INSERT INTO phpbb_portal_menu (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (8, 'icon_menu_012.png', 'Media Player', 'portal/block/mp3_player_popup.php', '1', 5);
INSERT INTO phpbb_portal_menu (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (9, 'icon_menu_009.png', 'FAQ', 'faq.php', '1', 6);
INSERT INTO phpbb_portal_menu (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (10, 'icon_menu_021.gif', 'BBCode FAQ', 'faq.php?mode=bbcode', '1', 7);
INSERT INTO phpbb_portal_menu (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (11, 'icon_menu_001.gif', 'Term of use', 'ucp.php?mode=terms', '1', 8);
INSERT INTO phpbb_portal_menu (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (12, 'icon_menu_024.gif', 'Privacy policy', 'ucp.php?mode=privacy', '1', 9);
INSERT INTO phpbb_portal_menu (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (13, 'icon_menu_020.gif', 'Search', 'search.php', '1', 10);
INSERT INTO phpbb_portal_menu (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (14, 'icon_menu_009.png', 'New posts', 'search.php?search_id=newposts', '3', 22);
INSERT INTO phpbb_portal_menu (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (15, 'icon_menu_005.gif', 'Subscribed', 'ucp.php?i=main&amp;mode=subscribed', '3', 27);
INSERT INTO phpbb_portal_menu (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (16, 'icon_menu_017.png', 'Private messages', 'ucp.php?i=pm&amp;folder=inbox', '3', 28);
INSERT INTO phpbb_portal_menu (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (17, 'icon_menu_028.gif', 'Mod''s', 'portal/portal_mods.php', '1', 11);
INSERT INTO phpbb_portal_menu (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (18, 'icon_menu_022.gif', 'Portal pages', 'portal_pages.php', '1', 14);
INSERT INTO phpbb_portal_menu (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (19, 'icon_menu_011.gif', 'Acronyms', 'portal/portal_acronyms.php', '1', 20);
INSERT INTO phpbb_portal_menu (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (20, 'information.png', 'Recent Topics', 'portal/portal_recent_topics.php', '1', 5);

# -- phpbb_portal_mods
INSERT INTO phpbb_portal_mods (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (1, 'Manage Mods Database', '1.0', '', 'Manage Mods Database for XL 5.0 Portal, create/edit/delete Mods fully ACP aware.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/');
INSERT INTO phpbb_portal_mods (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (2, 'phpBB3 Portal XL 5.0', 'Plain', '', 'phpBB3 Portal XL 5.0 ~ Your insane crazy portal system for phpBB3 which is fully ACP aware. Thank you for choosing phpBB3 Portal XL 5.0. ACP settings by DaMysterious 2007.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/');
INSERT INTO phpbb_portal_mods (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (3, 'Manage Partners 88x31', '1.0', '', 'Manage Partner banner exchange, banner size 88x31. You can create/edit/delete a partners Items. Max image size 88x31 pixel, bigger images will be resized to that value in the portal block. You can add as much partners as you like to show in this block, but there is a limit for random display of 6 logo''s simultaneously to not overload the server.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/');
INSERT INTO phpbb_portal_mods (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (4, 'Manage Banners 400x60', '1.0', '', 'Manage banner exchange, banner size 400x60. You can create/edit/delete a partners Items. Max image size 400x60 pixel, bigger images will be resized to that value in the portal block. You can add as much banners as you like to show in this block, but there is a limit for random display of 1 logo.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/');
INSERT INTO phpbb_portal_mods (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (5, 'Manage Banners 130x600', '1.0', '', 'Manage banner exchange, banner size 130x600. You can create/edit/delete a partners Items. Max image size 130x600 pixel, bigger images will be resized to that value in the portal block. You can add as much banners as you like to show in this block, but there is a limit for random display of 1 logo.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/');
INSERT INTO phpbb_portal_mods (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (6, 'Navigation Menu management', '1.0', '', 'You can create/edit/move/delete a custom Menu Item. This menu block can be switched on/off. Path is relative to the forums root directory, i.e. &quot;http://www.yourdomain.com/&quot; for a external link. Internal links can be added like &quot;portal.php&quot; to call a certain file from your site, or &quot;memberlist.php?mode=leaders&quot; to call a certain function of your forum from out of the navigation menu. ', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/');
INSERT INTO phpbb_portal_mods (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (7, 'Quotation management', '1.0', '', 'You can create/edit/delete Quotes. This menu block can be switched on/off. You can add as much quotations as you like to show in this block, but there is a limit for random display of 1 quote set.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/');
INSERT INTO phpbb_portal_mods (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (8, 'Links management', '1.0', '', 'You can create/edit/move/delete a custom link Item. This menu block can be switched on/off. Path is relative to the forums root directory, i.e. &quot;http://www.yourdomain.com/&quot; for a external link.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/');
INSERT INTO phpbb_portal_mods (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (9, 'Scroll Message', '1.0', '', 'The marquee tag is a non-standard HTML markup element type which causes text onscreen to scroll from right to left across the screen. The default width of the MARQUEE element is equal to the width of its parent element.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/');
INSERT INTO phpbb_portal_mods (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (10, 'META Tags', '1.0', '', 'Welcome to the META Tags managment. These tags allow you to give a description of your website to the search engine to allow them indexing your site.\nIt is why, you should take attention.\nFurthermore of referencing, these tags allow other options such as automatic redirect to another URL.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/');
INSERT INTO phpbb_portal_mods (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (11, 'RSS syndication messages', '1.0', '', 'RSS (which, in its most recent format, stands for &quot;Really Simple Syndication&quot;). RSS content can be read using software called a &quot;feed reader&quot; or an &quot;aggregator.&quot; The user subscribes to a feed by entering the feed''s link into the reader or by clicking an RSS icon in a browser that initiates the subscription process. The reader checks the user''s subscribed feeds regularly for new content, downloading any updates that it finds. ', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/');
INSERT INTO phpbb_portal_mods (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (12, 'RSS syndication attachments', '1.0', '', 'RSS (which, in its most recent format, stands for &quot;Really Simple Syndication&quot;). RSS content can be read using software called a &quot;feed reader&quot; or an &quot;aggregator.&quot; The user subscribes to a feed by entering the feed''s link into the reader or by clicking an RSS icon in a browser that initiates the subscription process. The reader checks the user''s subscribed feeds regularly for new content, downloading any updates that it finds. ', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/');
INSERT INTO phpbb_portal_mods (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (13, 'Forum Adds Management', '1.0', '', 'Displays advertisements in the viewtopic screen. You can choose the forums where the advertisement will be shown, you can even choose who can see the advertisement (guest or registered). You can set where the advertisemt appears (top, bottom or after every post). Furthermore all adds will be displayed randomly.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/');
INSERT INTO phpbb_portal_mods (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (14, 'Portal Pages', '1.0', '', 'This MOD allows the admin to add custom pages using phpBB3''s Portal ACP. The entries can be edited, as they are stored into the database.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/');
INSERT INTO phpbb_portal_mods (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (15, 'Tooltip control', '1.0', '', 'Show the title attribute in a tooltip popup div.', 'http://www.pragt.info/html/techniek9e.php', 'H.M. Pragt', 'http://www.pragt.info/html/techniek9e.php');
INSERT INTO phpbb_portal_mods (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (16, 'JavaScript-based PNG fix', 'v1.0', '', 'Correctly handle PNG transparency in Win IE 5.5 &amp; 6.', 'http://homepage.ntlworld.com/bobosola', 'Bob Osola', 'http://homepage.ntlworld.com/bobosola');
INSERT INTO phpbb_portal_mods (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (17, 'lastRSS', '0.9.1', '', 'Simple yet powerfull PHP class to parse RSS files. Database bridge to Portal XL 5.0 by DaMysterious 2007.', 'http://lastrss.webdot.cz/', 'Vojtech Semecky', 'http://lastrss.webdot.cz/');
INSERT INTO phpbb_portal_mods (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (18, 'Portal Acronyms', '1.0', '', 'Give you the ability to have a table with words and descriptions, who can be displayed as a lexicon and also can be used to automatic insert acronyms with Tooltips to all posts. Based on Acronym Mod from CodeMonkeyX using phpBB3''s Portal ACP.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/');
INSERT INTO phpbb_portal_mods (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (19, 'Animate Digits IP Tracking Counter', '0.4.0', '', 'This MOD adds a digits visit counter for your phpBB with following features:\n+ Enable/Disable IP Tracking (with IP tracking, we have &quot;IP Visit Counter&quot;, with no IP tracking, we have &quot;Hits Visit Counter&quot; :p).\n+ Set number of digits for counter (from 1 to maximize).\n+ Reset counter (started date time &amp; hits value) from ACP.\n+ Animate effect from counter images when reload (if you select display as images in counter display mode from ACP).\n+ Custom display mode of counter: No display/Display as images/Display as text\n+ Enable/Disable display counter statistics.\n+ With some other settings in ACP...', 'http://www.vinabb.com', 'nedka', 'http://www.vinabb.com');

# -- phpbb_portal_newsfeeds
INSERT INTO phpbb_portal_newsfeeds (feed_id, feed_title, feed_show, feed_url, feed_position) VALUES (1, 'Next Generation', 1, 'http://www.next-gen.biz/rss.xml', 2);
INSERT INTO phpbb_portal_newsfeeds (feed_id, feed_title, feed_show, feed_url, feed_position) VALUES (2, 'Tom''s Hardware', 1, 'http://www.tomshardware.com/motherboard/headlines.rss', 2);
INSERT INTO phpbb_portal_newsfeeds (feed_id, feed_title, feed_show, feed_url, feed_position) VALUES (3, 'Tom''s Hardware', 1, 'http://www.tomshardware.com/cpu/headlines.rss', 1);
INSERT INTO phpbb_portal_newsfeeds (feed_id, feed_title, feed_show, feed_url, feed_position) VALUES (4, 'ign.com', 1, 'http://scripts.ign.com/rss/ign.Xbox360.2.0.xml', 2);
INSERT INTO phpbb_portal_newsfeeds (feed_id, feed_title, feed_show, feed_url, feed_position) VALUES (5, 'ign.com', 1, 'http://scripts.ign.com/rss/ign.PC.2.0.xml', 1);
INSERT INTO phpbb_portal_newsfeeds (feed_id, feed_title, feed_show, feed_url, feed_position) VALUES (6, 'BBC News Front Page UK Edition', 1, 'http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/front_page/rss.xml', 1);
INSERT INTO phpbb_portal_newsfeeds (feed_id, feed_title, feed_show, feed_url, feed_position) VALUES (7, 'CNN World', 1, 'http://rss.cnn.com/rss/cnn_world.rss', 1);
INSERT INTO phpbb_portal_newsfeeds (feed_id, feed_title, feed_show, feed_url, feed_position) VALUES (8, 'Discovery headlines', 1, 'http://dsc.discovery.com/news/xml/top-stories.xml', 2);

# -- phpbb_portal_pages
INSERT INTO phpbb_portal_pages (page_id, page_index, page_edit, page_title, page_alias, page_disable, page_order, page_position, page_last_position, page_view, page_img, page_content, enable_bbcode, enable_smilies) VALUES (1, 0, 0, 'login_box.html', 'Login/Out', 0, 1, '3', '', '1', 'user.png', '', 1, 1);
INSERT INTO phpbb_portal_pages (page_id, page_index, page_edit, page_title, page_alias, page_disable, page_order, page_position, page_last_position, page_view, page_img, page_content, enable_bbcode, enable_smilies) VALUES (2, 0, 0, 'portal_pages.html', 'Portal XL 5.0 ~ Plain', 0, 34, '2', '', '1', 'folder_link.png', '&lt;br&gt;\r\nPortal XL 5.0 ~ Plain along phpBB 3.0.x is released!\r\n&lt;br&gt;\r\n&lt;p&gt;Our latest FILE release is version ~ 5.0 and comes along &lt;a href=&quot;http://www.phpbb.com/downloads/&quot; class=&quot;external text&quot; title=&quot;http://www.phpbb.com/downloads/&quot; rel=&quot;nofollow&quot;&gt;phpBB 3.0.x&lt;/a&gt;.\r\n&lt;/p&gt;\r\n&lt;div align=&quot;center&quot;&gt;&lt;br /&gt;\r\n  &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;\r\n &lt;tr&gt;\r\n &lt;td width=&quot;50%&quot;&gt;&lt;div align=&quot;center&quot;&gt;&lt;a href=&quot;http://www.portalxl.nl/forum/&quot; class=&quot;image&quot; title=&quot;portalxl40_suite.png&quot;&gt;&lt;img src=&quot;portal/images/portalxl40_suite.png&quot; alt=&quot;portalxl40_suite.png&quot; width=&quot;280&quot; height=&quot;295&quot; hspace=&quot;10&quot; vspace=&quot;10&quot; /&gt;&lt;/a&gt;&lt;/div&gt;&lt;/td&gt;\r\n      &lt;td width=&quot;50%&quot; valign=&quot;top&quot;&gt;&lt;div align=&quot;left&quot;&gt;Portal XL 5.0 is a phpBB3 value-add that provides a portal frontend to the phpBB3 forum application. Portal XL 5.0 is tested to phpBB3.\r\n The portal is a flexible and powerful portal solution which is dynamic, advanced and complete in features and configuration via phpBB3''s ACP in a quick and efficient way. &lt;/div&gt;&lt;/td&gt;\r\n &lt;/tr&gt;\r\n &lt;/table&gt;\r\n &lt;/p&gt;\r\n&lt;/div&gt;', 1, 1);

# -- phpbb_portal_partners
INSERT INTO phpbb_portal_partners (partners_id, partners_url, partners_img, partners_description) VALUES (1, 'http://www.phpbb.com/', 'portal/images/banners/88x31/phpBB_88a.gif', 'phpBB Home site');
INSERT INTO phpbb_portal_partners (partners_id, partners_url, partners_img, partners_description) VALUES (2, 'http://www.zymic.com/', 'portal/images/banners/88x31/zymic.gif', 'Zymic');
INSERT INTO phpbb_portal_partners (partners_id, partners_url, partners_img, partners_description) VALUES (3, 'http://www.apachefriends.org/en/index.html', 'portal/images/banners/88x31/xampp.gif', 'XAMPP');
INSERT INTO phpbb_portal_partners (partners_id, partners_url, partners_img, partners_description) VALUES (4, 'http://www.portalxl.nl/forum/', 'portal/images/banners/88x31/poweredby_portalXL40_88x31.png', 'Home site of Portal XL 5.0');
INSERT INTO phpbb_portal_partners (partners_id, partners_url, partners_img, partners_description) VALUES (5, 'http://awstats.sourceforge.net/', 'portal/images/banners/88x31/awstats.png', 'AWStats');
INSERT INTO phpbb_portal_partners (partners_id, partners_url, partners_img, partners_description) VALUES (6, 'http://www.mylimages.com/prive/portal.php', 'portal/images/banners/88x31/sgo_logo.gif', 'Mylimages par SGo');
INSERT INTO phpbb_portal_partners (partners_id, partners_url, partners_img, partners_description) VALUES (7, 'http://www.mysql.com/', 'portal/images/banners/88x31/my_sql_database_engine.bmp', 'MySql Database Engine');
INSERT INTO phpbb_portal_partners (partners_id, partners_url, partners_img, partners_description) VALUES (8, 'http://www.openssl.org/', 'portal/images/banners/88x31/openssl_button.gif', 'OpenSSL');
INSERT INTO phpbb_portal_partners (partners_id, partners_url, partners_img, partners_description) VALUES (9, 'http://zinloosgeweld.nl', 'portal/images/banners/88x31/ikbentegenzinloosgeweld88x31.gif', 'Ik Ben Tegen Zinloos Geweld');
INSERT INTO phpbb_portal_partners (partners_id, partners_url, partners_img, partners_description) VALUES (10, 'http://www.portalxl.nl/forum/', 'portal/images/banners/88x31/damysterious_logo.gif', 'Home site of Portal XL 5.0');

# -- phpbb_portal_quote
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (1, 'Marriage is one of the chief causes of divorce...', 'Unknown');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (2, 'Women are like hurricanes: when they come they are wet and wild, and when they leave they take the house and the car...', 'Unknown');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (3, 'There is two theories to aruguing with women. Neither one works...', 'Unknown');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (4, 'Some people are funny. They spend money they do not have, to buy things they do not need, to impress people they do not like...', 'Unknown');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (5, 'Sometimes i think i understand everything. Then i regain consciousness...', 'Unknown');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (6, 'Life is what happens to us while we are making other plans...', 'Unknown');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (7, 'Masturbation is nothing to be ashamed of. It is nothing to be particularly proud of, either...', 'Unknown');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (8, 'You can go a long way with a smile. You can go a lot farther with a smile and a gun...', 'Unknown');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (9, 'A friend: someone who likes you even after they know you...', 'Unknown');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (10, 'Creativity is great, but plagiarism is faster...', 'Unknown');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (15, 'A friend is one who knows us, but loves us anyway.', 'Fr. Jerome Cummings');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (16, 'Remember, the greatest gift is not found in a store nor under a tree, but in the hearts of true friends.', 'Cindy Lew');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (17, 'Who finds a faithful friend, finds a treasure.', 'Jewish Saying');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (18, 'Love is like a booger.  You keep picking at it until you get it, then wonder what to do with it.', 'Unknown');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (19, 'My father used to play with my brother and me in the yard.  Mother would come out and say, &quot;You''re tearing up the grass.&quot;  &quot;We''re not raising grass,&quot; Dad would reply.  &quot;We''re raising boys.&quot;', 'Harmon Killebrew');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (20, 'It is not flesh and blood but the heart which makes us fathers and sons.', 'Johann Schiller');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (21, 'With men he can be rational and unaffected, but when he has ladies to please, every feature works.', 'Jane Austen');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (22, 'As Homer would say, Woo-hoo!', 'Simpsons');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (23, 'The truth that makes men free is for the most part the truth which men prefer not to hear.', 'Herbert Agar');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (24, 'What greater thing is there for two human souls that to feel that they are joined... to strengthen each other... to be at one with each other in silent unspeakable memories.', 'George Eliot');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (25, 'In the arithmetic of love, one plus one equals everything, and two minus one equals nothing.', 'Mignon McLaughlin');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (26, 'For one human being to love another that is perhaps the most difficult of our tasks; the ultimate, the last test and proof; the work for which all other work is but preparation.', 'Rainer Maria Rilke');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (27, 'Love works in miracles every day: such as weakening the strong, and stretching the weak; making fools of the wise, and wise men of fools; favouring the passions, destroying reason, and in a word, turning everything topsy-turvy.', 'Marguerite De Valois');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (28, 'The truth [is] that there is only one terminal dignity-love.  And the story of a love is not important-what is important is that one is capable of love. It is perhaps the only glimpse we are permitted of eternity.', 'Helen Hayes');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (29, 'Happiness isn''t something you experience; it''s something you remember.', 'Oscar Levant');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (30, 'Saying what we think gives us a wider conversational range than saying what we know.', 'Cullen Hightower');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (31, 'If you pick up a starving dog and make him prosperous, he will not bite you. This is the principal difference between a dog and a man.', 'Mark Twain');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (32, 'An author is a fool who, not content with boring those he lives with, insists on boring future generations.', 'Charles de Montesquieu');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (33, 'People often say that ''beauty is in the eye of the beholder'', and I say that the most liberating thing about beauty is realizing that you are the beholder. This empowers us to find beauty in places where others have not dared to look, including inside ourselves.', 'Salma Hayek');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (34, 'A dog will look up on you; a cat will look down on you; however, a pig will see you eye to eye and know it has found an equal.', 'Churchill');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (35, 'Computers make it easier to do a lot of things, but most of the things they make it easier to do don''t need to be done.', 'Andy Rooney');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (36, 'If language is not correct, then what is said is not what is meant; if what is said is not what is meant, then what must be done remains undone; if this remains undone, morals and art will deteriorate; if justice goes astray, the people will stand about in helpless confusion. Hence there must be no arbitrariness in what is said. This matters above everything.', 'Confucius');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (37, 'Don''t do things half-assed. If a thing is worth doing at all, it''s worth doing as well as you can possibly do it. Pick out something you think is worthwhile and do it or work at it with passion. Do it with all your might.', 'Hugh Young');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (38, 'Better stop short than fill to the brim. Oversharpen the blade, and the edge will soon blunt. Amass a store of gold and jade, and no one can protect it. Claim wealth and titles, and disaster will follow. Retire when the work is done. This is the way of heaven.', 'Tao Te Ching');
INSERT INTO phpbb_portal_quote (quote_id, quote, quote_author) VALUES (39, 'I know that most men, including those at ease with problems of the greatest complexity, can seldom accept even the simplest and most obvious truth if it be such as would oblige them to admit the falsity of conlusions which they have delighted in explaining to colleages, which they have proudly taught to others, and which they have woven, thread by thread, into the fabric of their lives.', 'Leo Tolstoy');

# -- phpbb_portal_acronyms
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (1, 'MOD', 'Modification');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (2, 'Modlist', 'List of modifications');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (3, 'phpBB', 'php Bulletin Board version I');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (4, 'phpBB2', 'php Bulletin Board  version II');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (5, 'Schei&szlig;e', '- we don''t need such insults here -');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (6, 'Fuck you', '- we don''t need such words here -');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (7, '24/7', '24 hours a day, 7 days a week');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (8, 'AAMOF', 'As A Matter Of Fact');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (9, 'ACP', 'Administrative Control Panel');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (10, 'AFAIAA', 'As Far As I Am Aware');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (11, 'AFAIK', 'As Far As I Know');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (12, 'AI', 'Artificial Intelligence');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (13, 'ASAP', 'As Soon As Possible');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (14, 'b/c', 'because');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (15, 'BS', 'Bull Shit');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (16, 'btw', 'By The Way');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (17, 'CMX', 'CodeMonkeyX');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (18, 'FAQ', 'Frequently Asked Question');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (19, 'FNA', 'ForumNews Advance');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (20, 'FTP', 'File Transfer Protocol');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (21, 'KB', 'Knowledge Base');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (22, 'LOI', 'Lack Of Interest');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (23, 'LOL', 'Laughing Out Loud');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (24, 'LOLAROTG', 'Laughing Out Loud And Rolling On The Ground');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (25, 'M$', 'Micro');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (26, 'OSM', 'OpenSiteManager');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (27, 'PEBCAK', 'Problem Exists Between Chair And Keyboard');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (28, 'POS', 'Piece Of ***');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (29, 'PS', 'Post Scriptum');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (30, 'ROFL', 'Rolling On Floor Laughing');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (31, 'TTM', 'To The Moderator');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (32, 'w/', 'with');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (33, 'w/o', 'without');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (34, 'wywiwyg', 'What You Write Is What You Get');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (35, 'styles', 'Skins for your running script');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (36, '2S2D', 'Double Sided Double Density');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (37, '3GPP', 'Third Generation Partnership Project');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (38, '4CC', 'Four-character Code');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (39, 'AA', 'Ascii Art');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (40, 'AAA', 'Automatic Artwork Alignment');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (41, 'A&amp;B bit signaling', 'Procedure used in T1 transmission facilities in which each of the 24 T1 subchannels devotes 1 bit of every sixth frame to the carrying of supervisory signaling information. Also called 24th channel signaling.');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (42, 'access server', 'Communications processor that connects asynchronous devices to a LAN or WAN through network and terminal emulation software. Performs both synchronous and asynchronous routing of supported protocols. Sometimes called a network access server.');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (43, 'active hub', 'A multiported device that amplifies LAN transmission signals.');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (44, '2L8', 'Too late');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (45, '2U2', 'To you too');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (46, '4GM', 'Forgive me');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (47, 'AFK', 'Away from keyboard');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (48, 'ASL', 'Age, sex, location?');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (49, 'ASLP', 'Age, sex, location, picture?');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (50, 'ATM', 'At the moment');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (51, 'ATYS', 'Anything you say');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (52, 'AWA', 'As well as');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (53, 'B4', 'Before');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (54, 'B4N', 'Bye for now');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (55, 'CHMOD', ' A UNIX command that changes the mode of a file. There are three modes a file can have turned on or off: read ability, write ability, and execute ability. Each mode can be set for either the owner, the members of the owner''s group, or all users.');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (56, 'NAN', 'No Answer Needed');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (57, 'BTW', 'By the way');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (58, 'XL 5.0', 'phpBB3 Portal XL 5.0 ~ Your insane crazy portal system for phpBB3');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (59, 'mod', 'Modification');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (60, 'Acronym', 'Acronyms and initialisms are abbreviations, such as NATO, laser, and IBM, that are formed using the initial letters of words or word parts in a phrase or name.');
INSERT INTO phpbb_portal_acronyms (acronym_id, acronym, description) VALUES (61, 'phpBB3', 'php Bulletin Board version III');

# -- phpbb_portal_banners_ho
INSERT INTO phpbb_portal_banners_ho (banners_id, banners_url, banners_img_hor, banners_description) VALUES (1, 'http://www.portalxl.nl/forum/', 'portal/images/banners/400x60/damysterious.xs4all.nl.gif', 'Home of phpBB3 Portal XL 5.0');
INSERT INTO phpbb_portal_banners_ho (banners_id, banners_url, banners_img_hor, banners_description) VALUES (2, 'http://www.portalxl.nl/forum/', 'portal/images/banners/400x60/damysterious.xs4all.nl.jpg', 'Home of phpBB3 Portal XL 5.0');

# -- phpbb_portal_banners_ve
INSERT INTO phpbb_portal_banners_ve (banners_id, banners_url, banners_img_ver, banners_description) VALUES (1, 'http://www.doom3.com/', 'portal/images/banners/130x600/portal_doom3.jpg', 'Doom 3 science fiction horror first-person shooter computer game');
INSERT INTO phpbb_portal_banners_ve (banners_id, banners_url, banners_img_ver, banners_description) VALUES (2, 'http://www.ryzom.com/', 'portal/images/banners/130x600/portal_SagaOfRyzom.jpg', 'Ryzom - Science-Fantasy MMORPG Emphasising Universe, Freedom, Roleplay and Community');
INSERT INTO phpbb_portal_banners_ve (banners_id, banners_url, banners_img_ver, banners_description) VALUES (3, 'http://www.portalxl.nl/forum/', 'portal/images/banners/130x600/portal_sandman.jpg', 'Home of phpBB3 Portal XL 5.0');
INSERT INTO phpbb_portal_banners_ve (banners_id, banners_url, banners_img_ver, banners_description) VALUES (4, 'http://www.electronicarts.co.uk/games/349/', 'portal/images/banners/130x600/portal_easpawn.jpg', 'A dark hero, troubled with the dual aspects of good and evil found in all people.');
INSERT INTO phpbb_portal_banners_ve (banners_id, banners_url, banners_img_ver, banners_description) VALUES (5, '', 'portal/images/banners/130x600/portal_jbond.jpg', '');
INSERT INTO phpbb_portal_banners_ve (banners_id, banners_url, banners_img_ver, banners_description) VALUES (6, '', 'portal/images/banners/130x600/portal_starwars.gif', '');
INSERT INTO phpbb_portal_banners_ve (banners_id, banners_url, banners_img_ver, banners_description) VALUES (7, '', 'portal/images/banners/130x600/portal_wowbanner.jpg', '');
INSERT INTO phpbb_portal_banners_ve (banners_id, banners_url, banners_img_ver, banners_description) VALUES (8, 'http://www.portalxl.nl/forum/', 'portal/images/banners/130x600/portal_skulls.jpg', 'Home of phpBB3 Portal XL 5.0');
INSERT INTO phpbb_portal_banners_ve (banners_id, banners_url, banners_img_ver, banners_description) VALUES (9, '', 'portal/images/banners/130x600/portal_redfaction.jpg', '');
INSERT INTO phpbb_portal_banners_ve (banners_id, banners_url, banners_img_ver, banners_description) VALUES (10, '', 'portal/images/banners/130x600/portal_praetorians.jpg', '');
INSERT INTO phpbb_portal_banners_ve (banners_id, banners_url, banners_img_ver, banners_description) VALUES (11, '', 'portal/images/banners/130x600/portal_matrix.jpg', '');
INSERT INTO phpbb_portal_banners_ve (banners_id, banners_url, banners_img_ver, banners_description) VALUES (12, '', 'portal/images/banners/130x600/portal_lotrtt.gif', '');
INSERT INTO phpbb_portal_banners_ve (banners_id, banners_url, banners_img_ver, banners_description) VALUES (13, '', 'portal/images/banners/130x600/portal_lotr.jpg', '');
INSERT INTO phpbb_portal_banners_ve (banners_id, banners_url, banners_img_ver, banners_description) VALUES (14, '', 'portal/images/banners/130x600/portal_guildwars.jpg', '');

# -- phpbb_portal_block
INSERT INTO phpbb_portal_block (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (1, 0, 0, 'welcome.html', 'Welcome', 0, 2, '2', '', '1', 'heart.png', '');
INSERT INTO phpbb_portal_block (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (2, 0, 0, 'login_box.html', 'Login/Out', 0, 1, '3', '', '1', 'user.png', '');
INSERT INTO phpbb_portal_block (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (3, 0, 0, 'main_menu.html', 'Navigation', 0, 1, '1', '', '1', 'folder_find.png', '');
INSERT INTO phpbb_portal_block (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (4, 0, 0, 'clock.html', 'Clock', 0, 2, '1', '', '1', 'layout.png', '');
INSERT INTO phpbb_portal_block (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (5, 0, 0, 'center_recent.html', 'Recent News', 0, 3, '2', '', '1', 'folder_page.png', '');
INSERT INTO phpbb_portal_block (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (6, 0, 0, 'banners_horizontal.html', 'Banners', 0, 1, '2', '', '5', 'folder_link.png', '');
INSERT INTO phpbb_portal_block (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (7, 0, 0, 'quotes.html', 'Quotes of the day', 0, 4, '2', '', '1', 'folder_page.png', '');
INSERT INTO phpbb_portal_block (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (8, 0, 0, 'center_news.html', 'News', 0, 7, '2', '', '1', 'page_edit.png', '');
INSERT INTO phpbb_portal_block (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (9, 0, 0, 'link_us.html', 'Link to us', 0, 3, '1', '', '1', 'folder_link.png', '');
INSERT INTO phpbb_portal_block (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (10, 0, 0, 'partners.html', 'Affiliates', 0, 4, '1', '', '1', 'folder_link.png', '');
INSERT INTO phpbb_portal_block (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (11, 0, 0, 'stat_adv.html', 'Statistics', 0, 2, '3', '', '2', 'chart_bar.png', '');
INSERT INTO phpbb_portal_block (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (12, 0, 0, 'banners_vertical.html', 'Banners', 0, 3, '3', '', '1', 'folder_link.png', '');
INSERT INTO phpbb_portal_block (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (13, 0, 0, 'syndicate.html', 'Syndicate', 0, 4, '3', '', '1', 'page_white_text.png', '');
INSERT INTO phpbb_portal_block (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (14, 0, 0, 'google_adds_top.html', 'Google Top', 1, 1, '4', '', '5', 'chart_bar.png', '');
INSERT INTO phpbb_portal_block (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (15, 0, 0, 'google_adds_bottom.html', 'Google Bottom', 1, 1, '5', '', '5', 'chart_bar.png', '');

# -- phpbb_portal_block_index
INSERT INTO phpbb_portal_block_index (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (5, 0, 0, 'login_box.html', 'Login/Out', 0, 24, '3', '', '1', 'user_add.png', NULL);
INSERT INTO phpbb_portal_block_index (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (6, 0, 0, 'clock.html', 'Clock', 0, 36, '1', '', '2', 'layout.png', NULL);
INSERT INTO phpbb_portal_block_index (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (8, 0, 0, 'google_adds_top.html', 'Google Top', 1, 12, '4', '', '1', 'chart_bar.png', NULL);
INSERT INTO phpbb_portal_block_index (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (9, 0, 0, 'google_adds_bottom.html', 'Google Bottom', 1, 9, '5', '', '1', 'chart_bar.png', NULL);
INSERT INTO phpbb_portal_block_index (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (10, 0, 0, 'main_menu.html', 'Main Menu', 0, 29, '1', '', '1', 'key_add.png', NULL);
INSERT INTO phpbb_portal_block_index (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (11, 0, 0, 'banners_horizontal.html', 'Banners', 0, 6, '2', '', '1', 'folder_link.png', NULL);
INSERT INTO phpbb_portal_block_index (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (13, 0, 0, 'quotes.html', 'Quotes of the day', 0, 20, '2', '', '1', 'folder_page.png', NULL);
INSERT INTO phpbb_portal_block_index (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (49, 0, 0, 'main_menu.html', 'Main Menu', 0, 32, '3', '', '1', 'key_go.png', NULL);
INSERT INTO phpbb_portal_block_index (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (30, 0, 0, 'link_us.html', 'Link to us', 0, 42, '1', '', '1', 'folder_link.png', NULL);
INSERT INTO phpbb_portal_block_index (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (35, 0, 0, 'partners.html', 'Affiliates', 0, 51, '1', '', '1', 'folder_link.png', NULL);
INSERT INTO phpbb_portal_block_index (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (38, 0, 0, 'stat_adv.html', 'Statistics', 0, 42, '3', '', '2', 'chart_bar.png', NULL);
INSERT INTO phpbb_portal_block_index (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (46, 0, 0, 'banners_vertical.html', 'Banners', 1, 43, '3', '', '1', 'folder_link.png', NULL);
INSERT INTO phpbb_portal_block_index (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (47, 0, 0, 'syndicate.html', 'Syndicate', 0, 44, '3', '', '1', 'page_white_text.png', NULL);
INSERT INTO phpbb_portal_block_index (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (48, 0, 0, 'center_forumblock.html', 'Forum', 0, 22, '2', '', '1', 'page_edit.png', NULL);

