<?php

$sql = array();

// -- phpbb_portal_config
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_attachments_number', '10', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_right_collumn_width', '180', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_left_collumn_width', '180', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_max_online_friends', '8', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_max_most_poster', '8', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_max_last_member', '10', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_poll_topic_id', '0', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_last_visited_bots_number', '8', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_pay_acc', 'your@paypal.com', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_pay_s_block', '0', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_pay_c_block', '0', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_recent_title_limit', '30', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_max_topics', '10', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_news_forum', '1,2', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_news_length', '550', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_number_of_news', '4', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_number_of_announcments', '2', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_announcments_day', '0', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_announcments_length', '600', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_global_announcments_forum', '0', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_word_graph_word_counts', '0', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_word_graph_max_words', '50', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_word_graph_ratio', '2', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_version', 'Plain 0.2', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_welcome_intro', '&lt;img src=&quot;images/Behinde.gif&quot; width=&quot;100&quot; height=&quot;75&quot; vspace=&quot;10&quot;  hspace=&quot;10&quot; align=&quot;left&quot;&gt;&lt;div align=&quot;left&quot;&gt;&lt;center&gt;Benvenuto su &lt;b&gt;phpBB3 Portal XL 5.0&lt;/b&gt;&lt;/center&gt;&lt;br /&gt;Questo &egrave il messaggio di benvenuto che puoi configurare dal tuo pannello amministrativo, puoi scrivere ci&ograve che vuoi e se vuoi puoi usare un messaggio per gli ospiti ed uno per gli utenti registrati. Grazie e buon divertimento!', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_welcome_back', '&lt;img src=&quot;images/Behinde.gif&quot; width=&quot;100&quot; height=&quot;75&quot; vspace=&quot;10&quot;  hspace=&quot;10&quot; align=&quot;left&quot;&gt;&lt;div align=&quot;left&quot;&gt;Benvenuto su &lt;b&gt;phpBB3 Portal XL 5.0&lt;/b&gt;&lt;/center&gt;&lt;br /&gt;Questo &egrave il messaggio di benvenuto che puoi configurare dal tuo pannello amministrativo, puoi scrivere ci&ograve che vuoi e se vuoi puoi usare un messaggio per gli ospiti ed uno per gli utenti registrati. Grazie e buon divertimento!', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_drag_drop', '0', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_visit_counter', '2', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_weather_zipcode', '41334', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_weather_alternate_url1', '', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_weather_alternate_url', '&lt;a href=&quot;http://weerkamer.nl/&quot; target=&quot;_BLANK&quot;&gt;&lt;img src=&quot;http://weerkamer.nl/weer/weeranimatie/weeranimatie.fpl&quot; width=&quot;110&quot; height=&quot;69&quot; border=&quot;0&quot;&gt;&lt;/a&gt;', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_weather_ger', '0', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_weather_alternate_url2', '', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_index_forum_block', '0', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_index_left_column', '0', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_index_left_collumn_width', '180', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_index_right_column', '1', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_index_right_collumn_width', '180', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_poll_forum_id', '2', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_poll_post_id', '0', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_index_layout', '1', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_max_lastvisits', '5', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_display', '1', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee', '1', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_fontcolor', '#ff0000', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_fontsize', '11', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_direction', 'left', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_speed', '2', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_text', 'Utilizza il testo che vuoi, anche html e crea un blocco in home page, potrai cos&igrave attirare l\'attenzione dei tuoi visitatori, ospiti o utenti...', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_scrolldelay', '2', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_align', 'middle', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_behavior', 'scroll', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_bgcolor', '', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_height', '', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_width', '90%', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_hspace', '', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_vspace', '', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_scroll_message_marquee_loop', '', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_redirect_url_time', '', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_redirect_url_adress', '', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_refresh', '', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_pragma', '', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_keywords', '', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_description', '', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_picture_resize', '450', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_layout', '1', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_author', '', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_identifier_url', '', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_reply_to', '', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_revisit_after', '15', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_category', '', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_copyright', '', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_generator', '', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_robots', 'index, follow, noodp', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_distribution', 'Global', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_date_creation_year', '2007', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_date_creation_month', '05', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_date_creation_day', '01', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_date_revision_year', '2007', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_date_revision_month', '08', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_meta_date_revision_day', '21', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_feeds_cache_time', '3600', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_feeds_items_limit', '5', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_feeds_random_limit', '4', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_acronyms_allow', '1', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_pages_left_collumn_width', '180', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_pages_right_collumn_width', '180', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_partners_display_value', '3', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_left_column', '1', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_right_column', '1', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_pages_layout', '1', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_pages_left_column', '0', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_pages_right_column', '1', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_counter_ip_logfile', 'images/counter/ip.txt', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_counter_digits_ani_path', 'images/counter/digits_ani', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_counter_digits_path', 'images/counter/digits', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_counter_block_ip', '1', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_counter_digits_height', '22', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_counter_digits_width', '16', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_counter_digits_number', '6', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_counter_block_time', '60', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_counter_display_mode', '1', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_counter_display_stats', '1', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_news_show_last_post', '1', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_show_tool_tips', '1', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_news_repository', '0', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_news_permissions', '0', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_show_all_news', '0', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_announcement_repository', '0', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_announcements_permissions', '0', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_show_all_announcements', '0', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_pages_page', '1', 0)";
$sql[] = "INSERT INTO " . PORTAL_CONFIG_TABLE . " (config_name, config_value, is_dynamic) VALUES ('portal_pages_page_number', '2', 0)";


// -- phpbb_portal_forumadds
$sql[] = "INSERT INTO " . PORTAL_FORUMADDS_TABLE . " (adds_id, adds_name, adds_code, adds_show_forums, adds_show_all_forums, adds_active, adds_views, adds_max_views, adds_position) VALUES (1, 'Scrivi il tuo titolo qui', 'Puoi aggiungere la tua pubblicit&agrave sul forum, puoi anche scegliere la posizione e a chi visualizzare questo messaggio:).', 2, 1, 3, 1, 500, 1)";
$sql[] = "INSERT INTO " . PORTAL_FORUMADDS_TABLE . " (adds_id, adds_name, adds_code, adds_show_forums, adds_show_all_forums, adds_active, adds_views, adds_max_views, adds_position) VALUES (2, 'Scrivi il tuo titolo qui', 'Puoi aggiungere la tua pubblicit&agrave sul forum, puoi anche scegliere la posizione e a chi visualizzare questo messaggio:).', 2, 1, 3, 1, 500, 2)";

// -- phpbb_portal_links
$sql[] = "INSERT INTO " . PORTAL_LINKS_TABLE . " (links_id, links_img, links_name, links_url, links_view, links_order) VALUES (1, 'square_orange.gif', 'phpBB Worldwide', 'http://www.phpbb.com/', '1', 2)";
$sql[] = "INSERT INTO " . PORTAL_LINKS_TABLE . " (links_id, links_img, links_name, links_url, links_view, links_order) VALUES (2, 'square_red.gif', 'DaMysterious Portal XL 5.0', 'http://www.portalxl.nl/forum/', '1', 15)";
$sql[] = "INSERT INTO " . PORTAL_LINKS_TABLE . " (links_id, links_img, links_name, links_url, links_view, links_order) VALUES (3, 'square_blue.gif', 'Portal XL supporto italiano', 'http://www.portalxl.eu', '1', 17)";

// -- phpbb_portal_menu
$sql[] = "INSERT INTO " . PORTAL_MENU_TABLE . " (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (1, 'icon_menu_004.gif', 'Portale', 'portal.php', '1', 1)";
$sql[] = "INSERT INTO " . PORTAL_MENU_TABLE . " (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (2, 'icon_menu_014.png', 'Forum', 'index.php', '1', 2)";
$sql[] = "INSERT INTO " . PORTAL_MENU_TABLE . " (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (3, 'icon_menu_001.gif', 'Lista utenti', 'memberlist.php', '3', 26)";
$sql[] = "INSERT INTO " . PORTAL_MENU_TABLE . " (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (4, 'icon_menu_027.gif', 'Staff', 'memberlist.php?mode=leaders', '3', 25)";
$sql[] = "INSERT INTO " . PORTAL_MENU_TABLE . " (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (5, 'icon_menu_013.png', 'Preferiti', 'ucp.php?i=main&amp;mode=bookmarks', '3', 24)";
$sql[] = "INSERT INTO " . PORTAL_MENU_TABLE . " (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (6, 'icon_menu_019.png', 'Profilo', 'ucp.php', '3', 23)";
$sql[] = "INSERT INTO " . PORTAL_MENU_TABLE . " (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (8, 'icon_menu_012.png', 'Media player', 'portal/block/mp3_player_popup.php', '1', 5)";
$sql[] = "INSERT INTO " . PORTAL_MENU_TABLE . " (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (9, 'icon_menu_009.png', 'Faq', 'faq.php', '1', 6)";
$sql[] = "INSERT INTO " . PORTAL_MENU_TABLE . " (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (10, 'icon_menu_021.gif', 'BBCode Faq', 'faq.php?mode=bbcode', '1', 7)";
$sql[] = "INSERT INTO " . PORTAL_MENU_TABLE . " (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (11, 'icon_menu_001.gif', 'Termini di uso', 'ucp.php?mode=terms', '1', 8)";
$sql[] = "INSERT INTO " . PORTAL_MENU_TABLE . " (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (12, 'icon_menu_024.gif', 'Privacy', 'ucp.php?mode=privacy', '1', 9)";
$sql[] = "INSERT INTO " . PORTAL_MENU_TABLE . " (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (13, 'icon_menu_020.gif', 'Ricerca', 'search.php', '1', 10)";
$sql[] = "INSERT INTO " . PORTAL_MENU_TABLE . " (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (14, 'icon_menu_009.png', 'Nuovi messaggi', 'search.php?search_id=newposts', '3', 22)";
$sql[] = "INSERT INTO " . PORTAL_MENU_TABLE . " (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (15, 'icon_menu_005.gif', 'Sottoscrizioni', 'ucp.php?i=main&amp;mode=subscribed', '3', 27)";
$sql[] = "INSERT INTO " . PORTAL_MENU_TABLE . " (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (16, 'icon_menu_017.png', 'Messaggi privati', 'ucp.php?i=pm&amp;folder=inbox', '3', 28)";
$sql[] = "INSERT INTO " . PORTAL_MENU_TABLE . " (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (17, 'icon_menu_028.gif', 'Mods', 'portal/portal_mods.php', '1', 11)";
$sql[] = "INSERT INTO " . PORTAL_MENU_TABLE . " (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (18, 'icon_menu_022.gif', 'Pagine Portale', 'portal_pages.php', '1', 14)";
$sql[] = "INSERT INTO " . PORTAL_MENU_TABLE . " (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (19, 'icon_menu_011.gif', 'Acronimi', 'portal/portal_acronyms.php', '1', 20)";
$sql[] = "INSERT INTO " . PORTAL_MENU_TABLE . " (menu_id, menu_img, menu_name, menu_url, menu_view, menu_order) VALUES (20, 'information.png', 'Argomenti recenti', 'portal/portal_recent_topics.php', '1', 5)";

// -- phpbb_portal_mods
$sql[] = "INSERT INTO " . PORTAL_MODS_TABLE . " (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (1, 'Gestione database mods', '1.0', '', 'Gestisce il tuo database mods per XL 5.0 Portal, crea/modifica/cancella i Mods nel tuo pannello di controllo ACP.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/')";
$sql[] = "INSERT INTO " . PORTAL_MODS_TABLE . " (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (2, 'phpBB3 Portal XL 5.0', 'Plain', '', 'phpBB3 Portal XL 5.0 ~ Il tuo insolito, folle portale per il tuo phpBB3 pienamente configurabile via ACP.  Grazie per la scelta di XL 5.0. Configurazioni ACP di DaMysterious 2007.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/')";
$sql[] = "INSERT INTO " . PORTAL_MODS_TABLE . " (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (3, 'Gestione partners 88x31', '1.0', '', 'Gestisci lo scambio banners con una dimensione di 88x31. Puoi creare/modificare/cancellare i tuoi partners. La dimensione massima &egrave di 88x31 pixel, le immagini pi&ugrave grandi saranno automaticamente ridimensionate nel blocco al valore di default. Puoi visualizzare tutti i banners che vuoi, ma i banners vengono mostrati uno per volta in modo casuale.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/')";
$sql[] = "INSERT INTO " . PORTAL_MODS_TABLE . " (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (4, 'Gestione Banners 400x60', '1.0', '', 'Gestisci lo scambio banners con una dimensione di 400x600. Puoi creare/modificare/cancellare i tuoi partners. La dimensione massima &egrave di 400x600 pixel, le immagini pi&ugrave grandi saranno automaticamente ridimensionate nel blocco al valore di default. Puoi visualizzare tutti i banners che vuoi, ma essi vengono mostrati uno per volta in modo casuale.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/')";
$sql[] = "INSERT INTO " . PORTAL_MODS_TABLE . " (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (5, 'Gestione banners 130x600', '1.0', '', 'Gestisci lo scambio banners con una dimensione di 130x600. Puoi creare/modificare/cancellare i tuoi partners. La dimensione massima &egrave di 130x600 pixel, le immagini pi&ugrave grandi saranno automaticamente ridimensionate nel blocco al valore di default. Puoi visualizzare tutti i banners che vuoi, ma essi vengono mostrati uno per volta in modo casuale.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/')";
$sql[] = "INSERT INTO " . PORTAL_MODS_TABLE . " (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (6, 'Gestione menu di navigazione', '1.0', '', 'Puoi creare/modificare/spostare/cancellare e personalizzare il tuo menu. Il blocco pu&ograve essere attivato o disattivato. Puoi aggiungere anche links esterni. I links interni possono essere aggiunti specificando il percorso relativo, ad esempio &quot;portal.php&quot; o &quot;memberlist.php?mode=leaders&quot; per attivare alcune funzioni particolari dal menu di navigazione al tuo forum.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/')";
$sql[] = "INSERT INTO " . PORTAL_MODS_TABLE . " (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (7, 'Gestione citazioni', '1.0', '', 'Puoi creare/modificare/cancellare le tue citazioni. Il relativo blocco pu&ograve essere attivato o disattivato, puoi aggiungere tutte le citazioni che desideri ma esse verranno visualizzate una alla volta ed in modo casuale.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/')";
$sql[] = "INSERT INTO " . PORTAL_MODS_TABLE . " (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (8, 'Gestione links', '1.0', '', 'Puoi creare/modificare/spostare/cancellare i tuoi links. Il blocco pu&ograve essere attivato o disattivato, puoi inserire links esterni o links interni.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/')";
$sql[] = "INSERT INTO " . PORTAL_MODS_TABLE . " (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (9, 'Messaggio scorrevole', '1.0', '', 'Con questo mod puoi creare un blocco da visualizzare in home page per attirare l\'attenzione dei tuoi utenti, puoi attivare la funzione del messaggio scorrevole ed aggiungere il tuo contenuto come meglio credi.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/')";
$sql[] = "INSERT INTO " . PORTAL_MODS_TABLE . " (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (10, 'META Tags', '1.0', '', 'Puoi gestire in maniera autonoma i tuoi meta-tags indispensabili per i motori di ricerca, ci sono tantissime funzioni configurabili tramite il tuo ACP.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/')";
$sql[] = "INSERT INTO " . PORTAL_MODS_TABLE . " (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (11, 'Gestione RSS messaggi', '1.0', '', 'I contenuti RSS possono essere letti utilizzando il software denominato &quot;feed reader&quot; o un &quot;aggregatore&quot;. L\'utente sottoscrive un feed, inserendo il link del feed nel lettore oppure cliccando l\'icona RSS in un browser che avvia il processo di abbonamento. Il lettore comunica all\'utente sottoscritto i nuovi contenuti, o il download di eventuali aggiornamenti che trova. Nel tuo ACP puoi gestire autonomamente i tuoi feeds.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/')";
$sql[] = "INSERT INTO " . PORTAL_MODS_TABLE . " (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (12, 'Gestione RSS allegati', '1.0', '', 'I contenuti RSS possono essere letti utilizzando il software denominato &quot;feed reader&quot; o un &quot;aggregatore&quot;. L\'utente sottoscrive un feed, inserendo il link del feed nel lettore oppure cliccando l\'icona RSS in un browser che avvia il processo di abbonamento. Il lettore comunica all\'utente sottoscritto i nuovi contenuti,  o il download di eventuali aggiornamenti che trova. Nel tuo ACP puoi gestire autonomamente i tuoi feeds.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/')";
$sql[] = "INSERT INTO " . PORTAL_MODS_TABLE . " (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (13, 'Gestione pubblicit&agrave nel forum', '1.0', '', 'Visualizza la pubblicit&agrave negli argomenti del forum. Puoi scegliere come e dove visualizzare la pubblicit&agrave (ospiti o utenti registrati), puoi scegliere la posizione tra quattro predefinite.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/')";
$sql[] = "INSERT INTO " . PORTAL_MODS_TABLE . " (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (14, 'Pagine portale', '1.0', '', 'Questo mod aggiunge la possibilit&agrave di creare pagine con il tuo contenuto, puoi creare le pagine come meglio credi aggiungendo il codice html che preferisci.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/')";
$sql[] = "INSERT INTO " . PORTAL_MODS_TABLE . " (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (15, 'Controllo tooltip', '1.0', '', 'Inserisci il titolo in un attributo div a popup', 'http://www.pragt.info/html/techniek9e.php', 'H.M. Pragt', 'http://www.pragt.info/html/techniek9e.php')";
$sql[] = "INSERT INTO " . PORTAL_MODS_TABLE . " (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (16, 'PNG fix basata su JavaScript', 'v1.0', '', 'Questa fix corregge la trasparenza delle immagini PNG in Win IE 5.5 &amp; 6.', 'http://homepage.ntlworld.com/bobosola', 'Bob Osola', 'http://homepage.ntlworld.com/bobosola')";
$sql[] = "INSERT INTO " . PORTAL_MODS_TABLE . " (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (17, 'Ultimo RSS', '0.9.1', '', 'Semplice ma potente classe PHP per il parsing dei file RSS. Database per Portal XL 5.0 di DaMysterious 2007.', 'http://lastrss.webdot.cz/', 'Vojtech Semecky', 'http://lastrss.webdot.cz/')";
$sql[] = "INSERT INTO " . PORTAL_MODS_TABLE . " (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (18, 'Gestione acronimi', '1.0', '', 'Puoi creare/modificare/cancellare i tuoi acronimi, la funzione dona un effetto molto particolare nei messaggi del forum, infatti ad ogni parola chiave - acronimo inserito nel database acronimi, crea un collegamento nel relativo forum purch&egrave sia citata la porola chiave. Facciamo un\'esempio se aggiungi nel tuo database l\'acronimo &quot;Cms&quot; con relativa descrizione, quando nel forum tu o un tuo utente scriver&agrave la parola &quot;Cms&quot; si attiver&agrave un collegamento con la tua descrizione all\'acronimo inserito e visualizzato.', 'http://www.portalxl.nl/forum/', 'DaMysterious', 'http://www.portalxl.nl/forum/')";
$sql[] = "INSERT INTO " . PORTAL_MODS_TABLE . " (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (19, 'Contatore e monitoraggio IP', '0.4.0', '', 'Questo MOD aggiunge un contatore di visite per il tuo phpBB ed ha le seguenti caratteristiche:\nAttiva/Disattiva il monitoraggio IP (con il monitoraggio IP, si ha a disposizione un &quot;Contatore di visite IP&quot;, senza il monitoraggio Ip si ha a disposizione solo le &quot;Maggiori visite&quot; :p).\nConfiguri il numero di cifre da visualizzare per il contatore.\nAzzeri il contatore (data inizio e valori) dal tuo ACP.\nPuoi animare gli effetti del tuo contatore con delle immagini.\nAttivi/disattivi la visualizzazioni delle statistiche.\nAltre configurazioni sono disponibili dal tuo ACP.', 'http://www.vinabb.com', 'nedka', 'http://www.vinabb.com')";
$sql[] = "INSERT INTO " . PORTAL_MODS_TABLE . " (mod_id, mod_title, mod_version, mod_version_type, mod_desc, mod_url, mod_author, mod_download) VALUES (20, 'phpBB3 Portal XL 5.0 e Premod italiano', 'Plain', '', 'Portal XL 5.0 e Premod phpBB3 sono il valore aggiunto, offrono un portale frontend per il forum phpBB3. Portal XL 5.0 e Premod sono testati per phpBB3. Il portale &egrave uno strumento flessibile e potente, una soluzione di portale dinamica e avanzata, offre complete funzionalit&agrave e la configurazione via phpBB3 ACP in maniera rapida ed efficace. Le nostra versioni sono completamente tradotte in italiano, database e dati di default compresi. Le traduzioni in italiano sono di Lucky.', 'http://www.portalxl.eu', 'Lucky', 'http://www.portalxl.eu')";

// -- phpbb_portal_newsfeeds
$sql[] = "INSERT INTO " . PORTAL_NEWSFEEDS_TABLE . " (feed_id, feed_title, feed_show, feed_url, feed_position) VALUES (1, 'Next Generation', 1, 'http://www.next-gen.biz/rss.xml', 2)";
$sql[] = "INSERT INTO " . PORTAL_NEWSFEEDS_TABLE . " (feed_id, feed_title, feed_show, feed_url, feed_position) VALUES (2, 'Tom''s Hardware', 1, 'http://www.tomshardware.com/motherboard/headlines.rss', 2)";
$sql[] = "INSERT INTO " . PORTAL_NEWSFEEDS_TABLE . " (feed_id, feed_title, feed_show, feed_url, feed_position) VALUES (3, 'Luckylab.eu', 1, 'http://www.luckylab.eu/feed', 1)";
$sql[] = "INSERT INTO " . PORTAL_NEWSFEEDS_TABLE . " (feed_id, feed_title, feed_show, feed_url, feed_position) VALUES (4, 'Portal XL Italia', 1, 'http://www.portalxl.eu/portal/syndicate.php', 2)";
$sql[] = "INSERT INTO " . PORTAL_NEWSFEEDS_TABLE . " (feed_id, feed_title, feed_show, feed_url, feed_position) VALUES (5, 'ign.com', 1, 'http://scripts.ign.com/rss/ign.PC.2.0.xml', 1)";
$sql[] = "INSERT INTO " . PORTAL_NEWSFEEDS_TABLE . " (feed_id, feed_title, feed_show, feed_url, feed_position) VALUES (6, 'BBC News Front Page UK Edition', 1, 'http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/front_page/rss.xml', 1)";
$sql[] = "INSERT INTO " . PORTAL_NEWSFEEDS_TABLE . " (feed_id, feed_title, feed_show, feed_url, feed_position) VALUES (7, 'CNN World', 1, 'http://rss.cnn.com/rss/cnn_world.rss', 1)";
$sql[] = "INSERT INTO " . PORTAL_NEWSFEEDS_TABLE . " (feed_id, feed_title, feed_show, feed_url, feed_position) VALUES (8, 'Discovery headlines', 1, 'http://dsc.discovery.com/news/xml/top-stories.xml', 2)";

// -- phpbb_portal_pages
$sql[] = "INSERT INTO " . PORTAL_PAGES_TABLE . " (page_id, page_index, page_edit, page_title, page_alias, page_disable, page_order, page_position, page_last_position, page_view, page_img, page_content, enable_bbcode, enable_smilies) VALUES (1, 0, 0, 'login_box.html', 'Info utenti', 0, 1, '3', '', '1', 'user.png', '', 1, 1)";
$sql[] = "INSERT INTO " . PORTAL_PAGES_TABLE . " (page_id, page_index, page_edit, page_title, page_alias, page_disable, page_order, page_position, page_last_position, page_view, page_img, page_content, enable_bbcode, enable_smilies) VALUES (2, 0, 0, 'portal_pages.html', 'Portal XL 5.0 ~ Plain', 0, 34, '2', '', '1', 'folder_link.png', '&lt;br&gt;\nPortal XL 5.0 ~ per phpBB 3.0.x finalmente online!\n&lt;br&gt;\n&lt;p&gt;La nostra ultima versione &egrave completamente tradotta in italiano ~ 5.0 &lt;/p&gt;\n&lt;div align=&quot;center&quot;&gt;&lt;br /&gt;\n  &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;\n &lt;tr&gt;\n &lt;td width=&quot;50%&quot;&gt;&lt;div align=&quot;center&quot;&gt;&lt;a href=&quot;http://www.portalxl.nl/forum/&quot; class=&quot;image&quot; title=&quot;portalxl40_suite.png&quot;&gt;&lt;img src=&quot;portal/images/portalxl40_suite.png&quot; alt=&quot;portalxl40_suite.png&quot; width=&quot;280&quot; height=&quot;295&quot; hspace=&quot;10&quot; vspace=&quot;10&quot; /&gt;&lt;/a&gt;&lt;/div&gt;&lt;/td&gt;\n      &lt;td width=&quot;50%&quot; valign=&quot;top&quot;&gt;&lt;div align=&quot;left&quot;&gt;Portal XL 5.0 phpBB3 &egrave il valore aggiunto, offre un portale frontend per il forum phpBB3. Portal XL 5.0 &egrave testato per phpBB3. \n  Il portale &egrave uno strumento flessibile e potente, una soluzione di portale dinamica e avanzata, offre complete funzionalit&agrave e la configurazione via phpBB3 ACP in maniera rapida ed efficace. &lt;/div&gt;&lt;/td&gt;\n &lt;/tr&gt;\n &lt;/table&gt;\n &lt;/p&gt;\n&lt;/div&gt;', 1, 1)";

// -- phpbb_portal_partners
$sql[] = "INSERT INTO " . PORTAL_PARTNERS_TABLE . " (partners_id, partners_url, partners_img, partners_description) VALUES (1, 'http://www.phpbb.com/', 'portal/images/banners/88x31/phpBB_88a.gif', 'phpBB Home site')";
$sql[] = "INSERT INTO " . PORTAL_PARTNERS_TABLE . " (partners_id, partners_url, partners_img, partners_description) VALUES (2, 'http://www.portalxl.nl/forum/', 'portal/images/banners/88x31/poweredby_portalXL40_88x31.png', 'Home site of Portal XL 5.0')";
$sql[] = "INSERT INTO " . PORTAL_PARTNERS_TABLE . " (partners_id, partners_url, partners_img, partners_description) VALUES (3, 'http://www.portalxl.eu', 'portal/images/banners/88x31/lucky88x31.gif', 'Portal XL Italia')";
$sql[] = "INSERT INTO " . PORTAL_PARTNERS_TABLE . " (partners_id, partners_url, partners_img, partners_description) VALUES (4, 'http://www.luckylab.eu', 'portal/images/banners/88x31/luckylab.jpg', 'Luckylab.eu')";

// -- phpbb_portal_quote
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (1, 'L\'uomo &egrave il solo animale capace di farsi stupido ...', 'Andre Glucksmann')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (2, 'Che fortuna possedere una grande intelligenza non ti mancano mai le sciocchezze da dire...', 'Anton Cechov')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (3, 'Vedi di non chiamare intelligenti solo quelli che la pensano come te...', 'Ugo Ojetti')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (4, 'Con le donne accade due volte di non saper cosa dire:all\'inizio e alla fine di un amore...', 'Gesualdo Bufalino')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (5, 'Non permettere alla lingua di oltrepassare il pensiero...', 'Anton Checov')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (6, 'E\' difficilissimo parlare molto senza dire qualcosa di troppo...', 'Luigi XIV')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (7, 'Ci sono persone che parlano, parlano ...finch&egrave trovano qualcosa da dire...', 'Sacha Guitry')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (8, 'Un uomo solo &egrave sempre in cattiva compagnia...', 'Paul Valery')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (9, 'Quello di cui ho paura non &egrave la morte, ma la solitudine...', 'August Strindberg')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (10, 'Tutto ci&ograve che merita di essere fatto merita di esser fatto bene...', 'Philip Chesterfield')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (11, 'Conoscere gli altri &egrave saggezza. Conoscere se stessi &egrave saggezza superiore...', 'Umberto Eco')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (12, 'E\' pericoloso essere sinceri, a meno che di non essere anche stupidi...', 'Geroge Bernard Shaw')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (13, 'L\'opposto della menzogna non &egrave la verit&agrave...', 'Cesare Cant&ugrave')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (14, 'Governare &egrave far credere...', 'Niccol&ograve Machiavelli')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (15, 'E\' impossibile godere a fondo l\'ozio se non si ha una quantit&agrave di lavoro da fare...', 'Jerome K.Jerome')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (16, 'La peggiore moneta con cui si possono pagare gli amici sono i consigli; l\'unica moneta buona sono i soccorsi...', 'Ferdinando Galiani')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (17, 'Gli uomini credeno volentieri ci&ograve che desiderano sia vero...', 'Caio Giulio Cesare')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (18, 'Tutti sanno che una cosa &egrave impossibile da realizzare, finch&egrave arriva uno sprovveduto che non lo sa e la inventa.', 'Albert Einstein')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (19, 'Vivi come se tu dovessi morire subito, pensa come se tu non dovessi morire mai', 'Giorgio Almirante')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (20, 'Non amare per paura di essere rifiutati &egrave come non vivere per paura di morire', 'Anonimo')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (21, 'Il miglior modo di amare una cosa &egrave pensare che potremmo perderla', 'Gilbert Keith Chesterton')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (22, 'I veri amici vedono i tuoi errori e ti avvertono: i falsi amici vedono allo stesso modo i tuoi errori e li fanno notare agli altri', 'Anonimo')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (23, 'La felicit&agrave non &egrave che una semplice equazione La realt&agrave divisa per le aspettative... Se troppo ti aspetti rimarrai sempre deluso... Se poco ti aspetti sarai sempre felice', 'Anonimo')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (24, 'Il tuo cuore &egrave un gabbiano che vola libero nei cieli della vita. Lascialo andare senza paura ti sapr&agrave condurre alla felicit&agrave', 'Sergio Bambaren')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (25, 'La Famiglia &egrave la Patria del core', 'Giuseppe Mazzini')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (26, 'Un bimbo impiega due anni per imparare a parlare, un uomo impiega una vita per imparare a tacere.', 'Anonimo')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (27, 'La vecchiaia &egrave l\'adolescenza dell\'infinito.', 'Victor Hugo')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (28, 'Un giorno le macchine riusciranno a risolvere tutti i problemi, ma mai nessuna di esse potr&agrave porne uno.', 'Albert Einstein')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (29, 'Il software &egrave come il sesso, &egrave migliore quando &egrave libero.', 'Linus Torvalds')";
$sql[] = "INSERT INTO " . PORTAL_QUOTE_TABLE . " (quote_id, quote, quote_author) VALUES (30, 'Spesso la paura di un male ci conduce ad uno peggiore.', 'Nicolas Boileau')";

// -- phpbb_portal_acronyms
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (1, 'MOD', 'Modifica o aggiunta')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (2, 'Modlist', 'Lista di modifiche')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (3, 'phpBB', 'php Bulletin Board versione I')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (4, 'phpBB2', 'php Bulletin Board versione II')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (5, 'Acronimi', 'Iniziale di una parola, come ad esempio NATO, e IBM.')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (6, 'CMS', 'Sistema di gestione dei contenuti')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (7, 'FAQ', 'Risposte alle domande frequenti')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (8, 'FTP', 'Protocollo di trasferimento file')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (9, 'ACP', 'Pannello di controllo amministrativo')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (10, 'wywiwyg', 'Quello che scrivi &egrave quello che vedi')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (11, 'stile', 'Stile per eseguire lo script, generalmente &egrave il tema usato in phpBB')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (12, 'XL 5.0', 'phpBB3 Portal XL 5.0 ~ il tuo insolito, folle portale per phpBB 3.0.x')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (13, 'moddati', 'Modificati')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (14, 'C/A', 'Cortese attenzione')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (15, 'CHMOD', 'E\' un comando dei sistemi operativi Unix e Unix-like, e pi&ugrave in generale dei sistemi POSIX, che modifica i permessi di file e directory.')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (16, 'htaccess', 'Il file htaccess &egrave un file di testo in formato ASCII che detta delle istruzioni al webserver apache.')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (17, 'PS', 'Post Scriptum')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (18, 'Todo list', 'Lista di cose da fare')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (19, 'phpBB3', 'php Bulletin Board versione III')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (20, 'cokies', 'Frammenti di testo inviati da un server ad un web client')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (21, 'PHP', 'PHP Hypertext Preprocessor, preprocessore di ipertesti.')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (22, 'Query', 'Interrogazione di un database in modo da ottenere dei dati contenuti in uno o pi&ugrave database.')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (23, 'Portale', 'In informatica un portale &egrave un sito web che costituisce un punto di partenza, una porta di ingresso, ad un gruppo consistente di risorse di Internet o di una intranet.')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (24, 'mysql', 'E\' un database management system (DBMS) relazionale, composto da un client con interfaccia a caratteri e un server.')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (25, 'phpmyadmin', 'E\' un\'applicazione PHP libera che consente di amministrare in modo semplificato database di MySQL tramite un qualsiasi browser.')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (26, 'AJAX', 'Una tecnica per sviluppare applicazioni web interattive e dinamiche')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (27, 'DST automatica', 'Consente di impostare l\'ora automaticamente')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (28, 'JQUERY', 'E\' una libreria JavaScript che semplifica i documenti HTML')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (29, 'JavaScript', 'E\' un linguaggio di scripting orientato agli oggetti comunemente usato nei siti web')";
$sql[] = "INSERT INTO " . PORTAL_ACRONYMS_TABLE . " (acronym_id, acronym, description) VALUES (30, 'SEO', 'search engine optimizator, ottimizzatore per i motori di ricerca')";

// -- phpbb_portal_banners_ho
$sql[] = "INSERT INTO " . PORTAL_BANNER_HO_TABLE . " (banners_id, banners_url, banners_img_hor, banners_description) VALUES (1, 'http://www.portalxl.nl/forum/', 'portal/images/banners/400x60/damysterious.xs4all.nl.gif', 'Home of phpBB3 Portal XL 5.0')";
$sql[] = "INSERT INTO " . PORTAL_BANNER_HO_TABLE . " (banners_id, banners_url, banners_img_hor, banners_description) VALUES (2, 'http://www.portalxl.nl/forum/', 'portal/images/banners/400x60/damysterious.xs4all.nl.jpg', 'Home of phpBB3 Portal XL 5.0')";
$sql[] = "INSERT INTO " . PORTAL_BANNER_HO_TABLE . " (banners_id, banners_url, banners_img_hor, banners_description) VALUES (3, 'http://www.portalxl.eu', 'portal/images/banners/400x60/portalxl.jpg', 'Il supporto italiano a Portal XL')";
$sql[] = "INSERT INTO " . PORTAL_BANNER_HO_TABLE . " (banners_id, banners_url, banners_img_hor, banners_description) VALUES (4, 'http://www.portalxl.eu', 'portal/images/banners/400x60/lucky400x60.gif', 'Portal XL Italia')";

// -- phpbb_portal_banners_ve
$sql[] = "INSERT INTO " . PORTAL_BANNER_VE_TABLE . " (banners_id, banners_url, banners_img_ver, banners_description) VALUES (1, 'http://www.doom3.com/', 'portal/images/banners/130x600/portal_doom3.jpg', 'Doom 3 science fiction horror first-person shooter computer game')";
$sql[] = "INSERT INTO " . PORTAL_BANNER_VE_TABLE . " (banners_id, banners_url, banners_img_ver, banners_description) VALUES (2, 'http://www.ryzom.com/', 'portal/images/banners/130x600/portal_SagaOfRyzom.jpg', 'Ryzom - Science-Fantasy MMORPG Emphasising Universe, Freedom, Roleplay and Community')";
$sql[] = "INSERT INTO " . PORTAL_BANNER_VE_TABLE . " (banners_id, banners_url, banners_img_ver, banners_description) VALUES (3, 'http://www.portalxl.nl/forum/', 'portal/images/banners/130x600/portal_sandman.jpg', 'Home of phpBB3 Portal XL 5.0')";
$sql[] = "INSERT INTO " . PORTAL_BANNER_VE_TABLE . " (banners_id, banners_url, banners_img_ver, banners_description) VALUES (4, 'http://www.electronicarts.co.uk/games/349/', 'portal/images/banners/130x600/portal_easpawn.jpg', 'A dark hero, troubled with the dual aspects of good and evil found in all people.')";
$sql[] = "INSERT INTO " . PORTAL_BANNER_VE_TABLE . " (banners_id, banners_url, banners_img_ver, banners_description) VALUES (5, '', 'portal/images/banners/130x600/portal_jbond.jpg', '')";
$sql[] = "INSERT INTO " . PORTAL_BANNER_VE_TABLE . " (banners_id, banners_url, banners_img_ver, banners_description) VALUES (6, '', 'portal/images/banners/130x600/portal_starwars.gif', '')";
$sql[] = "INSERT INTO " . PORTAL_BANNER_VE_TABLE . " (banners_id, banners_url, banners_img_ver, banners_description) VALUES (7, '', 'portal/images/banners/130x600/portal_wowbanner.jpg', '')";
$sql[] = "INSERT INTO " . PORTAL_BANNER_VE_TABLE . " (banners_id, banners_url, banners_img_ver, banners_description) VALUES (8, 'http://www.portalxl.nl/forum/', 'portal/images/banners/130x600/portal_skulls.jpg', 'Home of phpBB3 Portal XL 5.0')";
$sql[] = "INSERT INTO " . PORTAL_BANNER_VE_TABLE . " (banners_id, banners_url, banners_img_ver, banners_description) VALUES (9, '', 'portal/images/banners/130x600/portal_redfaction.jpg', '')";
$sql[] = "INSERT INTO " . PORTAL_BANNER_VE_TABLE . " (banners_id, banners_url, banners_img_ver, banners_description) VALUES (10, '', 'portal/images/banners/130x600/portal_praetorians.jpg', '')";
$sql[] = "INSERT INTO " . PORTAL_BANNER_VE_TABLE . " (banners_id, banners_url, banners_img_ver, banners_description) VALUES (11, '', 'portal/images/banners/130x600/portal_matrix.jpg', '')";
$sql[] = "INSERT INTO " . PORTAL_BANNER_VE_TABLE . " (banners_id, banners_url, banners_img_ver, banners_description) VALUES (12, '', 'portal/images/banners/130x600/portal_lotrtt.gif', '')";
$sql[] = "INSERT INTO " . PORTAL_BANNER_VE_TABLE . " (banners_id, banners_url, banners_img_ver, banners_description) VALUES (13, '', 'portal/images/banners/130x600/portal_lotr.jpg', '')";
$sql[] = "INSERT INTO " . PORTAL_BANNER_VE_TABLE . " (banners_id, banners_url, banners_img_ver, banners_description) VALUES (14, '', 'portal/images/banners/130x600/portal_guildwars.jpg', '')";

// -- phpbb_portal_block
$sql[] = "INSERT INTO " . PORTAL_BLOCK_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (1, 0, 0, 'welcome.html', 'Benvenuto', 0, 2, '2', '', '1', 'heart.png', '')";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (2, 0, 0, 'login_box.html', 'Info utenti', 0, 1, '3', '', '1', 'user.png', '')";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (3, 0, 0, 'main_menu.html', 'Menu', 0, 1, '1', '', '1', 'folder_find.png', '')";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (4, 0, 0, 'clock.html', 'Orologio', 0, 2, '1', '', '1', 'layout.png', '')";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (5, 0, 0, 'center_recent.html', 'Articoli recenti', 0, 3, '2', '', '1', 'folder_page.png', '')";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (6, 0, 0, 'banners_horizontal.html', 'Banners', 0, 1, '2', '', '5', 'folder_link.png', '')";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (7, 0, 0, 'quotes.html', 'Citazione del giorno', 0, 4, '2', '', '1', 'folder_page.png', '')";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (8, 0, 0, 'center_news.html', 'Articoli', 0, 7, '2', '', '1', 'page_edit.png', '')";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (9, 0, 0, 'link_us.html', 'Linkaci', 0, 3, '1', '', '1', 'folder_link.png', '')";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (10, 0, 0, 'partners.html', 'Affiliati', 0, 4, '1', '', '1', 'folder_link.png', '')";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (11, 0, 0, 'stat_adv.html', 'Statistiche', 0, 2, '3', '', '2', 'chart_bar.png', '')";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (12, 0, 0, 'banners_vertical.html', 'Banners', 0, 3, '3', '', '1', 'folder_link.png', '')";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (13, 0, 0, 'syndicate.html', 'Info RSS', 0, 4, '3', '', '1', 'page_white_text.png', '')";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (14, 0, 0, 'google_adds_top.html', 'Google Top', 1, 1, '4', '', '5', 'chart_bar.png', '')";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (15, 0, 0, 'google_adds_bottom.html', 'Google Bottom', 1, 1, '5', '', '5', 'chart_bar.png', '')";

// -- phpbb_portal_block_index
$sql[] = "INSERT INTO " . PORTAL_BLOCK_INDEX_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (5, 0, 0, 'login_box.html', 'Info utenti', 0, 24, '3', '', '1', 'user_add.png', NULL)";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_INDEX_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (6, 0, 0, 'clock.html', 'Orologio', 0, 36, '1', '', '2', 'layout.png', NULL)";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_INDEX_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (8, 0, 0, 'google_adds_top.html', 'Google Top', 1, 12, '4', '', '1', 'chart_bar.png', NULL)";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_INDEX_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (9, 0, 0, 'google_adds_bottom.html', 'Google Bottom', 1, 9, '5', '', '1', 'chart_bar.png', NULL)";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_INDEX_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (10, 0, 0, 'main_menu.html', 'Menu', 0, 29, '1', '', '1', 'key_add.png', NULL)";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_INDEX_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (11, 0, 0, 'banners_horizontal.html', 'Banners', 0, 6, '2', '', '1', 'folder_link.png', NULL)";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_INDEX_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (13, 0, 0, 'quotes.html', 'Citazione del giorno', 0, 20, '2', '', '1', 'folder_page.png', NULL)";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_INDEX_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (49, 0, 0, 'main_menu.html', 'Menu', 0, 32, '3', '', '1', 'key_go.png', NULL)";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_INDEX_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (30, 0, 0, 'link_us.html', 'Linkaci', 0, 42, '1', '', '1', 'folder_link.png', NULL)";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_INDEX_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (35, 0, 0, 'partners.html', 'Affiliati', 0, 51, '1', '', '1', 'folder_link.png', NULL)";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_INDEX_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (38, 0, 0, 'stat_adv.html', 'Statistiche', 0, 42, '3', '', '2', 'chart_bar.png', NULL)";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_INDEX_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (46, 0, 0, 'banners_vertical.html', 'Banners', 1, 43, '3', '', '1', 'folder_link.png', NULL)";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_INDEX_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (47, 0, 0, 'syndicate.html', 'Info RSS', 0, 44, '3', '', '1', 'page_white_text.png', NULL)";
$sql[] = "INSERT INTO " . PORTAL_BLOCK_INDEX_TABLE . " (block_id, block_index, block_edit, block_name, block_alias, block_disable, block_order, block_position, block_last_position, block_view, block_img, block_content) VALUES (48, 0, 0, 'center_forumblock.html', 'Forum', 0, 22, '2', '', '1', 'page_edit.png', NULL)";

?>
